### PR TITLE
Method modified for floating point and negatives.

### PR DESCRIPTION
**Pull request by Baron-Chen**

### CODE REVIEW

**Comment by bazzilic** [comment]
1. Uncomment the tests that were commented during development.
2. Remove dependency on `BigRationalLibrary` library for `BigRational` class, and re-implement the class yourself. As I understand, you don't use much from the library anyway.  
You can implement `public static implicit operator BigRational(BigInteger bi) { return new BigRational(bi, 1); }` to have automatic conversion from BigInteger to BigRational.
3. `Encrypt` should return a 1-dimensional byte array `byte[]` (not `byte[][]`). Same for `Decrypt`, `Multiply`, `Divide`. You can use simple encoding e.g., first bytes for length, then the data, so your `byte[][]` will look like `[length][data][length][data]`.  
Use this to see how to do variable byte length encoding: https://nlp.stanford.edu/IR-book/html/htmledition/variable-byte-codes-1.html.
4. Please make sure that your IDE is set to use 4 spaces instead of a tab symbol, and convert all tabs in your code to 4 spaces.
5. `Multiply` and `Divide` should be implemented in ElGamalExt.Homomorphism project completely, and in ElGamalExt you just call these methods from there.

**Comment by Baron-Chen** [comment]
For the En/Decryption, I have merged the byte[][] to just a byte[], but what I do is just create a 2 times long byte array and half put the encrypted numerator and another half the encrypted denominator, it that ok?

**Comment by Baron-Chen** [comment]
1. Uncommented the tests.
2. Removed dependency on BigRationalLibrary library for BigRational class, and created a new Struct named BigFraction
3. Encrypt now returns a 1-Dimensional array.
4. Converted all tabs in your code to 4 spaces.
5. Multiply and Divide have been implemented in ElGamalExt.Homomorphism project completely.
Btw, the ElGamalExt.Homomorphism uses a local dependency as the new version has not been released on nuget

**Comment by bazzilic** [comment]
All changes from this PR and additional changes on top of it were incorporated into branch `optimized`. Closing the PR.

**Pull request closed without merging**
