### PR TITLE
Replace native BigInteger Implemenation to .Net BigInteger implementation #9 

### PR DESCRIPTION
**Pull request by Nicholas-Chew**
All Unit Test passed. Also Compared and Unit Test with old Big Integer Implementation to ensure both yield similar result.

### CODE REVIEW

**Comment by bazzilic** [comment]
Why are you closing and reopening the PR?

**Comment by Nicholas-Chew** [comment]
Sorry, I clicked the wrong button for several times. I will take note!

**Comment by Nicholas-Chew** [comment]
I forced the key strength of the keys to decrement by 1 and it is now good. This ensure that the generated key will not have the extra 4 bit at the MSB that is to retain the sign.

**Comment by bazzilic** [comment]
Nicholas,

Take a look here: https://github.com/bazzilic/ElGamalExt/compare/5c00167f39857e118ed4298d9dd74463780c5a15...6445de0fdbab6f665cb396e5bd194f5f3c26a852

I have finished the migration to `System.Numerics.BigInteger`. Reducing the key length is not an option in this kind of projects. Instead, I extended the ciphertext block size to hold the extra 2 bytes, and also implemented a padding mode that takes into account how BigInteger is implemented with regards to positive/negative values.

A helpful way to understand that was to print out binary representations of a bunch of negative and positive BigIntegers and see what happens there, especially when a new byte is added to the byte array. If you don't yet use it, I recommend taking a look at LINQPad for this kind of experiments.

I have incorporated your commits and my commits on top of them into a new branch `ENH-MigratingToNumerics`, where this will reside for some time.

I am closing this PR as all the commits from it are in the new branch as well.

**Pull request closed without merging**
